#!/usr/bin/env node
var https=require('https');
var nozbe = {
    host: 'webapp.nozbe.com',
    port: 443
};

process.argv.forEach(function (val, index, array) {
//  console.log(index + ': ' + val);
    switch(val){
        case "projects":
        case "p":
        case "proj":
            nozbe.path="/api/projects/key-"+process.env.NOZBE_API_KEY
            var req = https.get(nozbe, function(response) {
              // handle the response
              var ans = '';
              response.on('data', function(chunk) {
                ans += chunk;
              });
              response.on('end', function() {
                var obj = JSON.parse(ans);
                for(var i=0; i<obj.length; i++){
                    proj = obj[i];
                    console.log(i + ': ' + proj.name + "("+proj.count+")");
                }
              });
            });
            req.on('error', function(e) {
              console.log("Got error: " + e.message);
            });
            break;
        case "contexts":
        case "c":
        case "con":
            nozbe.path="/api/contexts/key-"+process.env.NOZBE_API_KEY
            var req = https.get(nozbe, function(response) {
              // handle the response
              var ans = '';
              response.on('data', function(chunk) {
                ans += chunk;
              });
              response.on('end', function() {
                var obj = JSON.parse(ans);
                for(var i=0; i<obj.length; i++){
                    context = obj[i];
                    console.log(i + ': ' + context.name + "("+context.count+")");
                }
              });
            });
            req.on('error', function(e) {
              console.log("Got error: " + e.message);
            });
            break;
        case "actions":
        case "a":
        case "act":
            nozbe.path="/api/actions/what-next/key-"+process.env.NOZBE_API_KEY
            var req = https.get(nozbe, function(response) {
              // handle the response
              var ans = '';
              response.on('data', function(chunk) {
                ans += chunk;
              });
              response.on('end', function() {
                var obj = JSON.parse(ans);
                for(var i=0; i<obj.length; i++){
                    action = obj[i];
                    if (action.done==0){
                        console.log(i + ': ' + action.name );
                    }
                }
              });
            });
            req.on('error', function(e) {
              console.log("Got error: " + e.message);
            });
            break;
    }
});
