#!/usr/bin/env node
var https=require('https');
var program = require('commander');

program
  .version('0.0.1')

program.command('projects')
  .description('display all projects')
  .action(function(env, options){ 
    nozbe('projects', function(obj) {
        for(var i=0; i<obj.length; i++){
            proj = obj[i];
            console.log(i + ': ' + proj.name + "("+proj.count+")");
        }
    });
  });

program.command('contexts')
  .description('display all contexts')
  .action(function(env, options){ 
    nozbe('contexts', function(obj) {
        for(var i=0; i<obj.length; i++){
            context = obj[i];
            console.log(i + ': ' + context.name + "("+context.count+")");
        }
    });
  });

program.command('actions')
  .description('display all actions')
  .action(function(env, options){ 
    nozbe('actions/what-next', function(obj) {
        for(var i=0; i<obj.length; i++){
            action = obj[i];
            if (action.done==0){
                console.log(i + ': ' + action.name );
            }
        }
    });
  });

function nozbe(command, onend ){
    var opt = {
        host: 'webapp.nozbe.com',
        port: 443,
        path: "/api/"+command+"/key-"+process.env.NOZBE_API_KEY
    };
    var req = https.get(opt, function(response) {
      // handle the response
      var ans = '';
      response.on('data', function(chunk) {
          ans += chunk;
      });
      response.on('end', function(){
          var obj = JSON.parse(ans);
          onend(obj);
      });
    });
    req.on('error', function(e) {
      console.log("Got error: " + e.message);
    });
}

//console.dir(argv);

program.parse(process.argv)
